### ISSUE TITLE
When I click on payment button it shows only redirecting and these below errors on console?

### ISSUE THREAD

**Issue by tanuuu18** [adrianhajdin/ecommerce_sanity_stripe#18]
![Screenshot (70)](https://user-images.githubusercontent.com/60546683/168275179-8aa17371-eedc-4138-9e36-392589060d19.png)

**Comment by YanaKrukovets** [comment]
@tanu8een 
Hello,

Do you set an account or business name at [https://dashboard.stripe.com/account](url) ?

**Comment by miahthegreat** [comment]
@tanu8een 

What does your stripe.js file look like? It is passing the data correctly to the redirectToCheckout function?

**Comment by tanuuu18** [comment]
done
