### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by arec-colon-aldeguer320** [adrianhajdin/ecommerce_sanity_stripe#22]
![InkedapiKeyError2_LI](https://user-images.githubusercontent.com/94948263/168415580-e0f127ea-49bf-43ec-acb2-4309b7b9fec2.jpg)
After ending running terminal and running npm run dev again, I now have the following error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
It appears the environment variables are OK now and are not undefined.

**Comment by YanaKrukovets** [comment]
@arec-colon-aldeguer320 

Do you set an account or business name at your stripe account [https://dashboard.stripe.com/account](url) ?

**Comment by arec-colon-aldeguer320** [comment]
@YanaKrukovets thanks once again. This was the issue!
