### ISSUE TITLE
400 Bad Request after clicking on "Pay with Stripe" button

### ISSUE THREAD

**Issue by arec-colon-aldeguer320** [adrianhajdin/ecommerce_sanity_stripe#23]
After clicking on "Pay with Stripe" button the following error occurs: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.
I suspect it is because I am also getting a 400Bad Request too. The following code is my handleCheckout function in Cart.jsx: 
`const handleCheckout = async () => {
		const stripe = await getStripe();

		const response = await fetch("/api/stripe", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(cartItems),
		});

		if (response.statusCode === 500) return;

		const data = await response.json();

		toast.loading("Redirecting...");

		stripe.redirectToCheckout({ sessionId: data.id });
	};`
![apiKeyError3](https://user-images.githubusercontent.com/94948263/168420127-b5789aca-4e70-4bc2-b0ba-189d1c7dfd8a.PNG)

**Comment by YanaKrukovets** [comment]
@arec-colon-aldeguer320 
Hello,

Do you set an account or business name at [https://dashboard.stripe.com/account](url) ?

**Comment by YanaKrukovets** [comment]
@arec-colon-aldeguer320 

also you can check logs at [https://dashboard.stripe.com/test/logs](url) . Sometimes they provide how to fix the errors.

**Comment by arec-colon-aldeguer320** [comment]
@YanaKrukovets I just figured this out lol! Thank you this was the issue. [https://stackoverflow.com/questions/64476542/stripe-error-in-order-to-use-checkout-you-must-set-an-account-or-business-name](url)
