### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')   

### ISSUE THREAD

**Issue by Pannu786** [adrianhajdin/ecommerce_sanity_stripe#24]
hello party people 

I am stuck at 2:11. I should be able to see the added product into the cart but guess what I am getting this annoying error. I have tried everything I could double, but I couldn't find anything to fix it. I need your help here to continue. 

Cheers. @adrianhajdin 
![Screenshot 2022-05-17 221107](https://user-images.githubusercontent.com/43903886/168866029-1b80f745-0ffd-406b-aa2b-5baa8a18042f.png)
![Screenshot 2022-05-17 221843](https://user-images.githubusercontent.com/43903886/168866464-c30bf408-a9ff-4f93-af8f-f9a67dffd3a6.png)

**Comment by Pannu786** [comment]
HELPPPP !!!!!!!!!!!

**Comment by Pannu786** [comment]
I am still stuck!! and this is sucks.. I can't figure out what's going wrong here. HELPPPP

**Comment by miahthegreat** [comment]
@Pannu786 I ended up modifying the code a bit. You don't have to use the sort function. Also don't mind the classes, I styled mine with Tailwind.![image](https://user-images.githubusercontent.com/50857184/168981606-075b02db-33fc-420a-a629-ceac0d7e90e5.png)

**Comment by Pannu786** [comment]
wow, you are adding your own stuff and making changes, not like me(dumb zombie) haha.. This is cool that you are using tailwind for styling really impressive.  I tried replacing "item" with "product" but still got the same issue. 
![Screenshot 2022-05-18 130030](https://user-images.githubusercontent.com/43903886/168983609-c794cd0c-f08c-4d9b-870c-f65e0ebf5347.png)

**Comment by miahthegreat** [comment]
Can you post the code for the entire file for me please?

**Comment by Pannu786** [comment]
yes sure, sorry could fit the whole code on one page so I took 3 pages. Hope it is readable to you. 
![Screenshot 2022-05-18 132630](https://user-images.githubusercontent.com/43903886/168988232-42c9e3d0-8c4f-43cd-97d8-bb62ead4422c.png)
![Screenshot 2022-05-18 132702](https://user-images.githubusercontent.com/43903886/168988240-4fd07674-3c98-4307-b3a6-cb80b7a8578b.png)
![Screenshot 2022-05-18 132729](https://user-images.githubusercontent.com/43903886/168988243-6548ee76-27a9-4bdf-a8b1-60027c530334.png)

**Comment by miahthegreat** [comment]
When you console.log the product, is it showing an image array within the object?

**Comment by Pannu786** [comment]
Nope, I am not getting the object except the same errors. Do you think it could be something to do with the [slug] file or other from where I am getting the product properties?

![Screenshot 2022-05-18 134955](https://user-images.githubusercontent.com/43903886/168992416-15dc3d30-8170-4270-bc16-5259796b501f.png)

**Comment by miahthegreat** [comment]
It could be. I would double check the StateContext and slug to make sure the addToCart function is passing all the right information.

**Comment by Pannu786** [comment]
I know I am asking a lot but when you got time could you have a look? I am at that stage where I am gonna start to pull my hair 😓 


StateContext file

![Screenshot 2022-05-18 140838](https://user-images.githubusercontent.com/43903886/168996504-7dfc2521-d11c-46cd-b89b-7fd189a08076.png)
![Screenshot 2022-05-18 140913](https://user-images.githubusercontent.com/43903886/168996517-ffb8b588-633e-44cf-a84f-c396e3a13641.png)
![Screenshot 2022-05-18 140959](https://user-images.githubusercontent.com/43903886/168996518-9a9ec4f3-834c-46c7-b673-9136ca5abcf8.png)


slug file

![Screenshot 2022-05-18 142448](https://user-images.githubusercontent.com/43903886/169000040-310de287-2e46-46b1-86d2-e8c0352c4d63.png)
![Screenshot 2022-05-18 142521](https://user-images.githubusercontent.com/43903886/169000045-e4a8a347-b429-44c7-ba2d-1b0448767ce5.png)
![Screenshot 2022-05-18 142545](https://user-images.githubusercontent.com/43903886/169000046-b37995a3-8842-45e7-bf09-78ea0a61f241.png)
![Screenshot 2022-05-18 142606](https://user-images.githubusercontent.com/43903886/169000052-44213419-b392-47a8-b0a9-d7ae1c790512.png)
![Screenshot 2022-05-18 142629](https://user-images.githubusercontent.com/43903886/169000057-5da5437b-a69b-45a7-a916-f2318987095b.png)
![Screenshot 2022-05-18 142648](https://user-images.githubusercontent.com/43903886/169000060-74169760-85c7-434a-9670-8de42e7fd68e.png)

**Comment by miahthegreat** [comment]
@Pannu786 Try updating the onAdd function in StateContext with this logic.

![image](https://user-images.githubusercontent.com/50857184/169002726-911832cf-e865-4201-9fca-0ab7805753ea.png)

**Comment by Pannu786** [comment]
I tried but got another error. 
![Screenshot 2022-05-18 151101](https://user-images.githubusercontent.com/43903886/169009735-1c56649d-7c3e-4b1d-886f-e24b057323d2.png)

Thanks for the effort anyway.
