### ISSUE TITLE
After deploying, PAY WITH STRIPE button doesn't do anything, redirecting... popup doesn't appear 

### ISSUE THREAD

**Issue by shivam-jha2712** [adrianhajdin/ecommerce_sanity_stripe#66]
In local host it works fine but in hosting it does not works

**Comment by shivam-jha2712** [comment]
https://ecommerce-boat-headphones.netlify.app/  link to my site can you help me out

**Comment by shivam-jha2712** [comment]
In vercel also it is facing similar problem

**Comment by thunt4jr** [comment]
What is your fixed on this? The link you have provided is working.

**Comment by shivam-jha2712** [comment]
> What is your fixed on this? The link you have provided is working.

Could you please send me a video of it working please it will be a great help as from my side I am unable to go through the payment section and reach till the success section of the site

**Comment by shivam-jha2712** [comment]
could you work wit it by forking the repo and I would merge it. It would be a great help

**Comment by thunt4jr** [comment]
CTRL-F5 and try again from your link. https://ecommerce-boat-headphones.netlify.app/

It works fine on my end and it took me to your test mode page.

**Comment by shivam-jha2712** [comment]
> CTRL-F5 and try again from your link. https://ecommerce-boat-headphones.netlify.app/
> 
> It works fine on my end and it took me to your test mode page.

Ahhh Yes It does thanks for ou help I was stuck with this! Thank you a lot Brother..................❤
