### ISSUE TITLE
Stripe redirect to Checkout failed

### ISSUE THREAD

**Issue by abg1995** [adrianhajdin/ecommerce_sanity_stripe#94]
Hello, i keep getting this error.

IntegrationError: stripe.redirectToCheckout: You must provide one of lineItems, items, or sessionId

i checked everything else and it seems fine, stripe says in its website that this method is deprecated.

Is this method working for anyone or has found a way to overcome the issue?

**Comment by abg1995** [comment]
nvmd i fixed it

**Comment by tom318267** [comment]
How did you fix it? I'm still trying to figure it out

**Comment by abg1995** [comment]
> How did you fix it? I'm still trying to figure it out

this:

instead of the line  stripe.redirectToCheckout()

try     window.location.replace(data.url);
make sure there are no typos on the Stripe file in the api
